apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-hello
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-hello
    app.kubernetes.io/part-of: python-flask-hello
  name: python-flask-hello
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-flask-hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-flask-hello
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jjams-tenant/python-flask-hello/python-flask-hello@sha256:d32e74f69f94b495884df59ecd4c51621758de420983a5101615545b97962836
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
