apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-hello
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-hello
    app.kubernetes.io/part-of: python-flask-hello
  name: python-flask-hello
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python-flask-hello
status:
  loadBalancer: {}
